name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [assigned, opened, synchronize, reopened, edited, labeled, unlabeled]


jobs:
  test:
    name: k8s test
    runs-on: self-hosted #ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          path: scm

      - name: Build
        uses: ./.github/actions/maven
        with:
          args: package 

